//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dicung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public long id { get; set; }
        public string full_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string public_code { get; set; }
        public Nullable<System.DateTime> birth_day { get; set; }
        public string sex { get; set; }
        public Nullable<System.TimeSpan> time_go { get; set; }
        public Nullable<System.TimeSpan> time_to { get; set; }
        public string from_location { get; set; }
        public Nullable<double> long_from { get; set; }
        public Nullable<double> lat_from { get; set; }
        public string to_location { get; set; }
        public Nullable<double> long_to { get; set; }
        public Nullable<double> lat_to { get; set; }
        public Nullable<double> km1 { get; set; }
        public string type { get; set; }
        public string type_vehicle { get; set; }
        public string des { get; set; }
        public Nullable<int> group_id { get; set; }
        public string group_name { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<double> money { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<byte> group_by { get; set; }
        public Nullable<int> group_number { get; set; }
    }
}
