//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dicung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public int id { get; set; }
        public string c_key { get; set; }
        public Nullable<int> value { get; set; }
    }
}
