//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dicung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dicungDbEntities : DbContext
    {
        public dicungDbEntities()
            : base("name=dicungDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<config> configs { get; set; }
        public virtual DbSet<result_booking> result_booking { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<country_config> country_config { get; set; }
        public virtual DbSet<country_place_nearby> country_place_nearby { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
    }
}
