//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dicung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class journey
    {
        public long id { get; set; }
        public Nullable<long> book_id { get; set; }
        public string name { get; set; }
        public string from_location { get; set; }
        public Nullable<double> long_from { get; set; }
        public Nullable<double> lat_from { get; set; }
        public string to_location { get; set; }
        public Nullable<double> long_to { get; set; }
        public Nullable<double> lat_to { get; set; }
        public string type_jouney { get; set; }
        public string type_vehicle { get; set; }
        public string days_travel { get; set; }
        public Nullable<System.DateTime> date_travels { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public Nullable<bool> return_journey { get; set; }
        public Nullable<System.TimeSpan> return_time { get; set; }
        public string list_booking { get; set; }
        public Nullable<int> number_people { get; set; }
        public Nullable<bool> is_full { get; set; }
        public string des { get; set; }
        public Nullable<bool> is_notify { get; set; }
        public Nullable<double> km1 { get; set; }
        public Nullable<double> km2 { get; set; }
    }
}
